### ISSUE TITLE
새로운 레포지토리 파일 구조

### ISSUE THREAD

**Issue by KR-Rodolfo** [openSW-team4/Movolay#2]
프론트가 변경될 때마다 서버 레포지토리를 업데이트 하기가 쉽지 않아서 통합 레포지토리를 만들었습니다. 앞으로 필요한 프론트 작업들은 이 레포지토리를 이용하시면 될 것 같습니다! 다들 포크해 가셔요!

파일 위치는 다음과 같습니다.

HTML 파일
- views 디렉토리 안의 .ejs 파일들을 이용하시면 됩니다.
- 확장자는 .html이 아니라 .ejs입니다.
- ejs 파일은 기존 html 파일과 동일하다고 보시고 수정하시면 됩니다.

CSS 파일
public 디렉토리 안의 styles.css 파일을 이용하시면 됩니다.

**번거롭게 해드려서 죄송합니다..ㅜㅜ**

**Comment by hong-ch** [comment]
수고하셨어요 감사합니다!!
